#!/usr/bin/env python3
import argh
import aws
from util.retry import retry

def main(name, verbose=False):
    not_found = aws.client('dynamodb').exceptions.ResourceNotFoundException
    table = retry(aws.client('dynamodb').describe_table, not_found)(TableName=name)['Table']
    return table['TableArn']

if __name__ == '__main__':
    with aws.setup():
        argh.dispatch_command(main)
